# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim keybinds for navigation
unbind Up
unbind Down
unbind Left
unbind Right

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# enable mouse mode
set -g mouse on

# causes lag, and I don't use esc in any seqs
set -s escape-time 0

# vim colors
set -g default-terminal "xterm-256color"
