# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim keybinds for navigation
unbind Up
unbind Down
unbind Left
unbind Right

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# enable mouse mode
set -g mouse on

# vim colors
set -g default-terminal "xterm-256color"
