#!/bin/env bash

# Silence MOTD
touch ~/.hushlogin

# Install GH CLI
type -p yum-config-manager >/dev/null || sudo yum install yum-utils
sudo yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
sudo yum install -y gh

# Copy configs
cp ../vimrc ~/.vimrc
cp ../zshrc ~/.zshrc
cp ../tmux-remote.conf ~/.tmux.conf
mkdir -p ~/.config/starship
cp ../starship.toml ~/.config/starship/starship.toml

# Install zsh
sudo yum install -y zsh
sudo yum install -y util-linux-user
sudo chsh -s "$(which zsh)" ec2-user

# Install zoxide
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

# Install starship
curl -sS https://starship.rs/install.sh | sudo sh -s -- --yes

# Install node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install 20

# Install tldr
npm install -g tldr

# Install tmux and htop
sudo yum install -y tmux htop

# Git
git config --global user.name "David Young"
git config --global user.email "dichlorodiphen@gmail.com"

# Install C/C++ toolchain
sudo yum install -y cmake g++ clang-tools-extra

# Install jenv
git clone https://github.com/jenv/jenv.git ~/.jenv
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(jenv init -)"' >> ~/.zshrc
. ~/.zshrc
eval "$(jenv init -)"
jenv enable-plugin export

# Install Java
sudo yum install -y java-17-amazon-corretto-devel
sudo yum install -y java-21-amazon-corretto-devel
jenv add /usr/lib/jvm/java-17-amazon-corretto.x86_64
jenv add /usr/lib/jvm/java-21-amazon-corretto.x86_64
jenv global 17

# Install Gradle
gradle_version=8.10
gradle_filename="gradle-${gradle_version}-all.zip"
if [ ! -d "/opt/gradle" ]; then
  sudo mkdir /opt/gradle
  wget -c http://services.gradle.org/distributions/${gradle_filename}
  sudo unzip -q -d /opt/gradle ${gradle_filename}
  echo 'export GRADLE_HOME=/opt/gradle/gradle-8.10' >> ~/.zshrc
  echo 'export PATH=$PATH:$GRADLE_HOME/bin' >> ~/.zshrc
  rm ${gradle_filename}
fi

# Set up coc.nvim
cp coc-settings.json ~/.vim/coc-settings.json

# Install docker
sudo yum install -y docker
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
sudo systemctl start docker
sudo usermod -aG docker $USER

# Install docker-compose
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

# New shell
exec $SHELL -l
