# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # sensible defaults for tmux, will not override user's settings
set -g @plugin 'tmux-plugins/tmux-resurrect' # saves and restores workspace layout
set -g @plugin 'tmux-plugins/tmux-continuum' # saves and restore workspace layout
set -g @plugin 'catppuccin/tmux' # catppuccin theme

# catppuccin theme configuration
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_current_number "#I"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# tmux-resurrect + tmux-continuum
set -g @resurrect-strategy-nvim 'session' # restore Neovim sessions
set -g @continuum-save-interval '15' # save every 15 min
set -g @continuum-restore 'on' # automatic restore on startup

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# remap prefix from 'C-b' to 'C-space'
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# vim keybinds for navigation
unbind Up
unbind Down
unbind Left
unbind Right

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# R for quick config reload
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Quick session switching with fzf in a popup
bind s display-popup -E "tmux list-sessions -F '#{session_name}' \
  | fzf --reverse --header 'Switch Session' \
  | xargs tmux switch-client -t"

# quick terminal popup
bind g display-popup -w 80% -h 80% -E "tmux attach -t scratch || tmux new -s scratch"


# start numbering at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on # Re-number when closing windows

# enable mouse mode
set -g mouse on

# performance and responsiveness
set -sg escape-time 0 # No delay after Esc (critical for Neovim)
set -g focus-events on # Neovim autoread support
set -g history-limit 50000 # Generous scrollback without going crazy
set -g display-time 2000 # Status messages visible longer
set -g status-interval 3 # Refresh status bar every 3s

# vim colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm*:Tc"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
